### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by paulinar** [paulinar/listly#1]
My app is complete, please review. /cc @codepathreview @codepath

**Comment by nesquena** [comment]
Paulina,

Looks great! Nice to see you already added a bunch of the extensions, even including a splash screen and logo! Good to see that attention to detail in the first assignment. 

Reviewing your LinkedIn, it's not clear to me if you meet the [selection criteria](http://courses.codepath.com/snippets/intro_to_android/selection_criteria) for participating but your submission was strong so I'd like to setup a quick chat with you anyways.

This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a personalized code review for each submitted project once the bootcamp starts.

The next step is to **schedule a short 5-10 minute phone conversation** [here](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU). Navigate to [January 13th and dates onward](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work.

Please make sure to **include the best number** to reach you at in the scheduled event? Look forward to chatting soon!

**Comment by paulinar** [comment]
Hi Nathan,

Thank you for your kind words! I went ahead and picked an interview slot with my phone number included in the event description. Regarding the selection criteria, I believe your concern is related to the "2+ years of professional software development experience", but that I can explain during our Wednesday phone call. :)

I look forward to speaking with you!

Best,
Paulina
